[package]
name = "travel"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.59"
uuid = "1.8.0"
users = { path = "../users" }

[dev-dependencies]
test-utils = { path = "../../test-utils" }

[lib]
name = "travel"
path = "src/lib.rs"
