[package]
name = "core-where-were-we"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-sdk-dynamodb = "1.20.0"

[workspace]

members = [
    "app/users",
    "utils"
]
