services:
  project-doc:
    image: project-doc
    build:
      context: ./project
      dockerfile: Dockerfile
    command: bash -c "cp -r /node-modules/node_modules /code && npm run build && cp -a /code/build/. /build/"
    volumes:
      - "./project:/code"
      - "./build/project:/build"
    working_dir: "/code"

  core-where-were-we-doc:
    image: rust:1
    command: cargo doc --workspace --no-deps --document-private-items --target-dir /build
    volumes:
      - "../backend/core-where-were-we:/code"
      - "./build/core-where-were-we:/build/doc"
    working_dir: "/code"

  top-page-doc:
    image: top-page-doc
    build:
      context: ./top-page
      dockerfile: Dockerfile
    command: bash -c "cp -r /node-modules/node_modules /code && npm run build && cp -a /code/dist/. /build/"
    volumes:
      - "./top-page:/code"
      - "./build/top-page:/build"
    working_dir: "/code"
