version: "3.8"
services:
  project-doc:
    build: ./dockerfiles/project-document/Dockerfile
    command: bash -c "npm ci && npm run build && cp -a /code/build/. /build/"
    volumes:
      - "./project:/code"
      - "./build/project:/build"
    working_dir: "/code"

  core-where-were-we-doc:
    build: ./dockerfiles/rust-base/Dockerfile
    command: cargo doc --workspace --target-dir /build
    volumes:
      - "../backend/core-where-were-we:/code"
      - "./build/core-where-were-we:/build/doc"
    working_dir: "/code"
