version: "3"
services:
  project-doc:
    image: node:20
    command: bash -c "npm ci && npm run build && cp -a /code/build/. /build/"
    volumes:
      - "./project:/code"
      - "./build/project:/build"
    working_dir: "/code"