name: Deploy documents
#on:
#  push:
#    branches:
#      - develop

on:
  push

permissions:
  contents: write

#defaults:
#  run:
#    working-directory: ./docs

jobs:
#  deploy-document:
#    timeout-minutes: 5
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout Code
#        uses: actions/checkout@v4
#      - name: Set up Docker
#        uses: docker/setup-buildx-action@v3
#      - name: Build Documents
#        run: docker compose up
#      - name: update permissions
#        run: sudo chmod -R 777 ./build
#      - name: Deploy to GitHub Pages
#        uses: JamesIves/github-pages-deploy-action@v4
#        with:
#          folder: ./docs/build
#          token: ${{ secrets.GITHUB_TOKEN }}

  build-project-document:
    defaults:
      run:
        working-directory: ./docs/project
    timeout-minutes: 3
    name: Build project document to make sure it can be built
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
      - name: mkdir
        run: sudo mkdir /build && sudo chmod -R 777 /build
      - name: Install packages
        run: bun install
      - name: Build Project Doc
        run: bun run build --out-dir /build
      - name: out
        uses: actions/upload-artifact@v4
        with:
          name: project-page
          path: /build
          overwrite: true
          retention-days: 1

  build-top-page-document:
    defaults:
      run:
        working-directory: ./docs/top-page
    timeout-minutes: 3
    name: Build top page document to make sure it can be built
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
      - name: Install packages
        run: bun install
      - name: mkdir
        run: sudo mkdir /build && sudo chmod -R 777 /build
      - name: Build the top page Doc
        run: bun run build --outDir /build/top-page
      - name: out
        uses: actions/upload-artifact@v4
        with:
          name: top-page
          path: /build/top-page
          overwrite: true
          retention-days: 1

  build-core-were-were-we-doc:
    defaults:
      run:
        working-directory: ./backend/core-where-were-we
    timeout-minutes: 3
    name: Build top page document to make sure it can be built
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: mkdir
        run: sudo mkdir /build && sudo chmod -R 777 /build
      - name: build doc
        run: cargo doc --workspace --no-deps --document-private-items --target-dir /build
      - name: out
        uses: actions/upload-artifact@v4
        with:
          name: core-where-were-we
          path: /build/doc
          overwrite: true
          retention-days: 1

  deploy-document:
    timeout-minutes: 3
    name: Build top page document to make sure it can be built
    runs-on: ubuntu-latest
    needs:
      - build-project-document
      - build-top-page-document
      - build-core-were-were-we-doc
    steps:
      - name: mkdir
        run: sudo mkdir /build && sudo chmod -R 777 /build
      - uses: actions/download-artifact@v4
        with:
          path: /build
      - run: ls -R /build
