name: Deploy documents
on:
  push:
    branches:
      - develop

permissions:
  contents: write

defaults:
  run:
    working-directory: ./docs

jobs:
  deploy-document:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Build Documents
        run: docker compose up
      - name: update permissions
        run: sudo chmod -R 777 ./build
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./docs/build
          token: ${{ secrets.GITHUB_TOKEN }}
