name: Deploy documents
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

permissions:
  contents: write

defaults:
  run:
    working-directory: ./docs

jobs:
  deploy-document:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Build Documents
        run: docker compose up project
      - run: ls
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com