name: Test Codes

on:
  pull_request:
    branches:
      - develop

jobs:
  test-core-where-were-we:
    timeout-minutes: 5
    name: test core www
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/core-where-were-we
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Add permission
        run: sudo chmod 777 -R ./
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      - name: Build Docker
        uses: docker/bake-action@v3
        with:
          files: |-
            ./docker-compose.yml
            ./docker-bake.hcl
          workdir: ./backend/core-where-were-we
      - name: Run test
        run: docker compose up app --exit-code-from app