name: Test Codes

on:
  pull_request:
    branches:
      - develop

jobs:
  test-core-where-were-we:
    name: test core www
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: set up rust
        run: rustup update stable && rustup default stable
      - name: check
        run: cargo check
        working-directory: ./backend/core-where-were-we
      - name: Run test
        run: cargo test --workspace
        working-directory: ./backend/core-where-were-we
