name: Test deployment

on:
  push

defaults:
  run:
    working-directory: ./docs

jobs:
  test-deploy:
    name: Test deployment to make sure it can be built
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker
        uses: docker/bake-action@v3
        with:
          files: |-
            ./docs/docker-compose.yml
            ./docs/docker-bake.hcl
          load: true
          push: false
      - name: Build documents
        run: docker compose up project-doc --exit-code-from project-doc