name: Test Document
#
#on:
#  pull_request:
#    branches:
#      - develop

on: push

jobs:
  test-project-document:
    defaults:
      run:
        working-directory: ./docs/project
    timeout-minutes: 3
    name: Build project document to make sure it can be built
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
      - name: ls
        run: echo $(ls)
      - name: Install packages
        run: bun install
      - name: Build Project Doc
        run: bun run build