name: Test deployment

on:
  pull_request:
    branches:
      - develop

defaults:
  run:
    working-directory: ./docs

jobs:
  test-deploy:
    name: Test deployment to make sure it can be built
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v4
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build documents
        run: docker compose up project-doc --exit-code-from project-doc