name: Test deployment

on:
  push

defaults:
  run:
    working-directory: ./docs

jobs:
  test-deploy:
    name: Test deployment to make sure it can be built
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      - name: Build Docker
        uses: docker compose build
      - name: Build documents
        run: docker compose up project-doc --exit-code-from project-doc