name: Test deployment

on:
  pull_request:
    branches:
      - develop

defaults:
  run:
    working-directory: ./docs

jobs:
  test-deploy:
    timeout-minutes: 5
    name: Test deployment to make sure it can be built
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker
        uses: docker/bake-action@v3
        with:
          files: |-
            ./docker-compose.yml
            ./docker-bake.hcl
          load: false
          push: true
          workdir: ./docs
      - name: Build documents
        run: docker compose up project-doc --exit-code-from project-doc