name: Test deployment

on:
  pull_request:
    branches:
      - develop

permissions:
  contents: write

defaults:
  run:
    working-directory: ./docs

jobs:
  test-deploy:
    name: Test deployment to make sure it can be built
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build documents
        run: docker compose up project-doc --exit-code-from project-doc
      - name: place
        run: echo ${PWD}
      - name: files
        run: ls
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
